CREATE TABLE IF NOT EXISTS manual_numbers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(30) NOT NULL,
    country_id INT DEFAULT 0,
    country_name VARCHAR(100) NOT NULL,
    service_code VARCHAR(20) NOT NULL DEFAULT 'tg',
    service_name VARCHAR(100) NOT NULL DEFAULT 'Telegram',
    cost_price DECIMAL(10,2) DEFAULT 0.00,
    sell_price DECIMAL(10,2) NOT NULL,
    notes VARCHAR(255) NULL,
    upload_batch VARCHAR(80) NULL,
    uploaded_by INT NOT NULL,
    sold_to INT NULL,
    status ENUM('available', 'sold', 'cancelled') DEFAULT 'available',
    sold_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_manual_phone_number (phone_number),
    KEY idx_manual_numbers_status_service (status, service_code),
    KEY idx_manual_numbers_sold_to (sold_to),
    CONSTRAINT fk_manual_numbers_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id),
    CONSTRAINT fk_manual_numbers_sold_to FOREIGN KEY (sold_to) REFERENCES users(id)
);
