<?php

return [
    'POST' => [
        '/auth/login' => 'Auth@login',
        '/auth/register' => 'Auth@register',
        '/auth/reset-password' => 'Auth@resetPassword',
        '/auth/refresh' => 'Auth@refresh',
        '/auth/logout' => 'Auth@logout',
        '/auth/biometric/challenge' => 'Auth@getBiometricChallenge',
        '/auth/biometric/register' => 'Auth@registerBiometric',
        '/auth/biometric/login-challenge' => 'Auth@getBiometricLoginChallenge',
        '/auth/biometric/verify' => 'Auth@verifyBiometric',
        '/auth/biometric/remove' => 'Auth@removeBiometric',
        '/admin/access-link' => 'AdminAccess@updateAdminConfig',
        '/products' => 'Products@create',
        '/categories' => 'Categories@create',
        '/orders' => 'Orders@create',
        '/orders/(\d+)/confirm-payment' => 'Orders@confirmPayment',
        '/reviews' => 'Reviews@create',
        '/uploads/catalog' => 'Uploads@catalog',
        '/sessions' => 'Sessions@create',
        '/telegram/webhook' => 'Telegram@handle',
        '/feedbacks' => 'Feedback@create',
        '/favorites/toggle' => 'Favorites@toggle',
        '/admin/store-settings' => 'Settings@updateAdminSettings',
    ],
    'GET' => [
        '/' => 'Orders@health',
        '/events/stream' => 'Events@stream',
        '/products' => 'Products@getAll',
        '/categories' => 'Categories@getAll',
        '/orders' => 'Orders@getAll',
        '/orders/(\d+)' => 'Orders@getOne',
        '/user/profile' => 'User@profile',
        '/reviews' => 'Reviews@getAll',
        '/analytics/summary' => 'Analytics@getSummary',
        '/analytics/sessions' => 'Analytics@getSessions',
        '/admin/access-link' => 'AdminAccess@getAdminConfig',
        '/admin/access-link/public' => 'AdminAccess@getPublicConfig',
        '/admin/store-settings' => 'Settings@getAdminSettings',
        '/store-settings/payment' => 'Settings@getPaymentSettings',
        '/feedbacks' => 'Feedback@getAll',
        '/favorites' => 'Favorites@list',
    ],
    'PUT' => [
        '/products/(\d+)' => 'Products@update',
        '/categories/(\d+)' => 'Categories@update',
        '/orders/(\d+)/status' => 'Orders@updateStatus',
        '/orders/(\d+)/payment-review' => 'Orders@reviewPayment',
        '/sessions/(.+)' => 'Sessions@update',
    ],
    'DELETE' => [
        '/products/(\d+)' => 'Products@delete',
        '/categories/(\d+)' => 'Categories@delete',
    ],
];
